apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-jgno
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-jgno
    app.kubernetes.io/part-of: load-app-9132dc24-c37f-4ab8-a82e-859dc02470eb
  name: devfile-sample-go-basic-j1tud
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-go-basic-jgno
    weight: null
status: {}
